[package]
name = "brainfuck_maker"
version = "0.1.0"
authors = ["guricerin <chanbo1e9@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
lazy_static = "1.4.0"
regex = "1.4.2"
